x-restart-policy: &restart-policy "no"
services:

  # ubuntu:
  #   image: lancache_ubuntu:latest
  #   platform: linux/arm64/v8
  #   build:
  #     context: ./ubuntu/

  # ubuntu-nginx:
  #   image: lancache_ubuntu-nginx:latest
  #   platform: linux/arm64/v8
  #   build:
  #     context: ./ubuntu-nginx/

  dns:
    image: pavelmc/lancache_dns:latest
    platform: linux/arm64/v8
    build:
      context: ./lancache-dns/
    env_file: .env
    restart: *restart-policy
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp

## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: *restart-policy
#    ports:
#      - 443:443/tcp

  monolithic:
    image: pavelmc/lancache_monolithic:latest
    platform: linux/arm64/v8
    build:
      context: ./monolithic/
    env_file: .env
    restart: *restart-policy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
